import "./globals.css";

import { Providers } from "@/app/redux/StoreProvider";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header>Header</header>
          <div className="container">{children}</div>
          <footer>Footer</footer>
        </Providers>
      </body>
    </html>
  );
}
