import "./globals.scss";

import { Providers } from "../app/redux/StoreProvider";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="main">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
