// import "@/app/globals.css";

import { Providers } from "@/app/redux/StoreProvider";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main>
      <div className="container aaaa">
        <h1>Admin layout</h1>
        {children}
      </div>
    </main>
  );
}
